### ISSUE TITLE
Do not manipulate the Options Parameters

### ISSUE THREAD

**Issue by dimified** [thenativeweb/terminal-img#6]
Thanks for the great talk @myposter and the thorough demonstration. As you were mentioning the manipulation of the options input parameter, I would like to address it here in this issue and propose an idea.

You are passing `requestedWidth` to the `image.resize` function but before you are manipulating the input parameter. You can avoid that by defining the `requestedWidth` with its default values instead of the options object. `Jimp.AUTO` will also be in this case not used as you are providing a valid default number 80 to the `options.width`. 

https://github.com/thenativeweb/terminal-img/blob/7534b70ff254ed3e2c506430da2cb90c141d2c04/lib/drawAsString.ts#L17

**Comment by goloroden** [comment]
Hi @dimified 👋 

Thanks a lot for your very nice feedback, and for submitting this idea 👍 

Would you mind coming up with a PR for this?

**Comment by dimified** [comment]
Great, I will do it.

**Comment by goloroden** [comment]
Thanks a lot 😊 

Please then also add yourself to the `package.json` file as contributor 😊

**Comment by goloroden** [comment]
@dimified I don't want to push, but any news on the PR?

**Comment by dimified** [comment]
Hi! I created a commit, but unfortunately I am not able to push. Are there any restrictions?

**Comment by susannaroden** [comment]
Hi @dimified 😊!

First of all I'd like to thank you for your support. The reason you can't simply push is that while the code is open to the public not everyone get's write access by default. Due to that fact you first have to fork the repo to get a writable copy of your own. Next step is to commit and push to your fork and then you can create a pull request on this basis. If you have any further questions don't hesitate to ask. Here's also a link to Github's documentation that explains the process: https://opensource.guide/how-to-contribute/#opening-a-pull-request

Have a nice day 👋

**Comment by goloroden** [comment]
Closed due to long inactivity.

**Comment by dimified** [comment]
Okay, you won. I will do it today :)
